#!/bin/bash
mkdir /wordpress1
mkdir -p /wordpress1/mysql/ && mkdir -p /wordpress1/wordpress/ && mkdir -p /wordpress1/phpfpm/app && mkdir -p /wordpress1/phpfpm/config && mkdir -p /wordpress1/nginx/config && cd .
z=`pwd`

cp startdb.sh /wordpress1/mysql
cp mysql_Dockerfile /wordpress1/mysql/Dockerfile

cp wordpress_Dockerfile /wordpress1/wordpress/Dockerfile
cp wordpress_run.sh /wordpress1/wordpress/run.sh

cp php-fpm.conf /wordpress1/phpfpm/config/
cp www.conf /wordpress1/phpfpm/config/
cp php_Dockerfile /wordpress1/phpfpm/Dockerfile
cp php_run.sh /wordpress1/phpfpm/run.sh

cp nginx.conf /wordpress1/nginx/config/
cp default.conf /wordpress1/nginx/config/
cp nginx_Dockerfile /wordpress1/nginx/Dockerfile


cd /wordpress1/mysql
docker build -t yousramagdy24/mysql .

cd /wordpress1/wordpress
docker build -t yousramagdy24/downloader .

cd /wordpress1/phpfpm/
docker build -t yousramagdy24/phpfpm .

cd /wordpress1/nginx/
docker build -t yousramagdy24/nginx .

rm -r /wordpress1

cd $z















